### ISSUE TITLE
Releasing bindings to Libuv 1.45.0 and 1.46.0

### ISSUE THREAD

**Issue by noib3** [bmatcuk/libuv-sys#7]
Libuv has released [2 minor versions](https://github.com/libuv/libuv/releases) since the last release of this crate. Is it possible to do two new separate releases?

If yes, please consider revisiting [this](https://github.com/bmatcuk/libuv-sys/pull/4) PR.

**Comment by bmatcuk** [comment]
Sorry, life's been busy. I released v1.45.0 and v1.46.0 just now, with the latest version of bindgen. I've also released a version of libuv-rs based on v1.45.0 with another based on v1.46.0 building as I type.

**Comment by noib3** [comment]
Thank you!

Now that bindgen has been updated would you consider merging #8?

**Comment by noib3** [comment]
Thank you!

Now that bindgen has been updated would you consider merging #8?
